import QtQuick
import QtMultimedia

// Chiptune sound effects and the two music loops, all generated by
// tools/make-sounds.py. `muted` silences everything; M toggles it in game.
Item {
  id: root

  property bool muted: false
  property real musicVolume: 0.55
  property real effectsVolume: 0.8
  // "theme", "travel" or "" for silence
  property string track: ""

  readonly property var names: ["blip", "select", "bonk", "coin", "pop", "clunk", "rumble", "splash", "death", "fanfare", "arrive", "rest", "ufo", "throw", "hit", "horn"]
  property var _effects: ({})

  function play(name) {
    if (muted || !name) return
    var e = _effects[name]
    if (e) e.play()
  }

  Repeater {
    model: root.names
    Item {
      id: holder
      required property string modelData
      SoundEffect {
        id: effect
        source: Qt.resolvedUrl("sounds/" + holder.modelData + ".wav")
        volume: root.effectsVolume
        muted: root.muted
      }
      Component.onCompleted: {
        var next = Object.assign({}, root._effects)
        next[modelData] = effect
        root._effects = next
      }
    }
  }

  MediaPlayer {
    id: music
    loops: MediaPlayer.Infinite
    audioOutput: AudioOutput {
      volume: root.muted ? 0 : root.musicVolume
    }
  }

  onTrackChanged: syncMusic()
  onMutedChanged: syncMusic()
  Component.onCompleted: syncMusic()

  function syncMusic() {
    if (!track || muted) { music.stop(); return }
    var src = Qt.resolvedUrl("sounds/" + track + ".wav")
    if (String(music.source) !== String(src)) { music.stop(); music.source = src }
    music.play()
  }
}
