import QtQuick

// Chiptune sound effects and the two music loops, all generated by
// tools/make-sounds.py. `muted` silences everything; M toggles it in game.
// The QtMultimedia half lives in SfxBackend.qml; if that module isn't
// installed the Loader fails quietly and the game plays on in silence.
Item {
  id: root

  property bool muted: false
  property real musicVolume: 0.55
  property real effectsVolume: 0.8
  // "theme", "travel" or "" for silence
  property string track: ""

  readonly property var names: ["blip", "select", "bonk", "coin", "pop", "clunk", "rumble", "splash", "death", "fanfare", "arrive", "rest", "ufo", "throw", "hit", "horn"]
  readonly property bool available: backend.status === Loader.Ready

  function play(name) {
    if (muted || !name || !available) return
    backend.item.play(name)
  }

  function syncMusic() {
    if (!available) return
    backend.item.music(muted ? "" : track)
  }

  Loader {
    id: backend
    source: Qt.resolvedUrl("SfxBackend.qml")
    onLoaded: {
      item.names = root.names
      root.syncMusic()
    }
    onStatusChanged: if (status === Loader.Error) console.warn("texodus: QtMultimedia isn't available, so the trail is silent (install your distro's Qt 6 multimedia QML module for sound)")
  }

  Binding { target: backend.item; property: "muted"; value: root.muted; when: root.available }
  Binding { target: backend.item; property: "musicVolume"; value: root.musicVolume; when: root.available }
  Binding { target: backend.item; property: "effectsVolume"; value: root.effectsVolume; when: root.available }

  onTrackChanged: syncMusic()
  onMutedChanged: syncMusic()
}
